Update .forgejo/workflows/update.yml

diff --git a/.forgejo/workflows/update.yml b/.forgejo/workflows/update.yml
--- a/.forgejo/workflows/update.yml
+++ b/.forgejo/workflows/update.yml
@@ -13,18 +13,27 @@ jobs:
         with:
           submodules: recursive
           fetch-depth: 0
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Configure Git
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
 
       - name: Update submodules
         run: git submodule update --remote --recursive
 
       - name: Commit and push changes
         run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
           if [[ -n $(git status -s) ]]; then
             git add .
             git commit -m "Update submodules to the latest commit"
-            git push
+            
+            # Try to push, if it fails, pull and try again
+            if ! git push; then
+              git pull --rebase
+              git push
+            fi
           else
             echo "No changes to commit"
           fi
