Update update.yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -1,53 +1,72 @@
 name: Update Submodules
+
 on:
-  schedule:
-    - cron: "0 */3 * * *"
-  workflow_dispatch:
+    schedule:
+        - cron: "0 */3 * * *"
+    workflow_dispatch:
 
 jobs:
-  update:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-        with:
-          submodules: recursive
-          fetch-depth: 0
-          token: ${{ secrets.GITHUB_TOKEN }}
+    update:
+        runs-on: ubuntu-latest
 
-      - name: Configure Git
-        run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
+        steps:
+            - name: Checkout repository
+              uses: actions/checkout@v3
+              with:
+                  submodules: recursive
+                  fetch-depth: 0
+                  token: ${{ secrets.GH_PAT }}
 
-      - name: Update submodules
-        run: |
-          git fetch origin
-          git reset --hard origin/main
-          git submodule update --remote --recursive
+            - name: Configure Git
+              run: |
+                  git config user.name "github-actions[bot]"
+                  git config user.email "github-actions[bot]@users.noreply.github.com"
 
-      - name: Commit and push changes
-        run: |
-          if [[ -n $(git status -s) ]]; then
-            git add .
-            git commit -m "Update submodules to the latest commit"
-            
-            # Try to push, if it fails, fetch, rebase, and try again
-            MAX_RETRIES=5
-            RETRY_COUNT=0
-            while ! git push && [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
-              git fetch origin
-              git rebase origin/main
-              RETRY_COUNT=$((RETRY_COUNT+1))
-              echo "Push failed. Retrying... (Attempt $RETRY_COUNT of $MAX_RETRIES)"
-            done
+            - name: Update submodules
+              run: |
+                  git fetch origin
+                  git reset --hard origin/main
+                  git submodule update --remote --recursive
 
-            if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
-              echo "Failed to push after $MAX_RETRIES attempts."
-              exit 1
-            fi
-          else
-            echo "No changes to commit"
-          fi
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            - name: Commit and push changes
+              run: |
+                  if [[ -n $(git status -s) ]]; then
+                    git add .
+                    git commit -m "Update submodules to the latest commit"
+
+                    # Try to push, if it fails, fetch, rebase, and try again
+                    MAX_RETRIES=5
+                    RETRY_COUNT=0
+                    while ! git push && [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
+                      git fetch origin
+                      git rebase origin/main
+                      RETRY_COUNT=$((RETRY_COUNT+1))
+                      echo "Push failed. Retrying... (Attempt $RETRY_COUNT of $MAX_RETRIES)"
+                    done
+
+                    if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
+                      echo "Failed to push after $MAX_RETRIES attempts."
+                      exit 1
+                    fi
+
+                    # Sync to mirror
+                    curl --fail -L \
+                      -X POST \
+                      -H "Accept: application/vnd.github+json" \
+                      -H "X-GitHub-Api-Version: 2022-11-28" \
+                      -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
+                      https://api.github.com/repos/${{ github.repository }}/actions/workflows/sync.yml/dispatches \
+                      -d '{"ref":"main"}'
+
+                    # Deploy GitHub Pages
+                    curl --fail -L \
+                      -X POST \
+                      -H "Accept: application/vnd.github+json" \
+                      -H "X-GitHub-Api-Version: 2022-11-28" \
+                      -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
+                      https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches \
+                      -d '{"ref":"main"}'
+
+                  else
+                    echo "No changes to commit"
+                  fi
